version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - notesnet

  app:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: notesdb
      DB_USER: notesuser
      DB_PASS: ${DB_PASS}
    depends_on:
      - db
    networks:
      - notesnet

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - notesnet

networks:
  notesnet:


